export const chapterData = {
    id: 1,
    title: "Introduction to Physics",
    description: "Basic concepts and fundamental principles of physics",
    totalLessons: 8,
    completedLessons: 3,
    lessons: [
      {
        id: 1,
        title: "What is Physics?",
        duration: "15 min",
        isCompleted: true,
        // Lesson-level videos
        videos: [
          {
            id: 1,
            title: "Introduction to Physics - Overview",
            duration: "12:30",
            thumbnail: "/placeholder.svg?height=200&width=300",
            videoUrl: "#",
          },
          {
            id: 2,
            title: "Why Study Physics?",
            duration: "8:45",
            thumbnail: "/placeholder.svg?height=200&width=300",
            videoUrl: "#",
          },
        ],
        notes: [
          {
            id: 1,
            title: "Definition and Scope",
            content:
              "Physics is the fundamental science that seeks to understand how the universe works. It deals with matter, energy, motion, forces, space, and time.",
            downloadUrl: "#",
            // Note-specific videos
            videos: [
              {
                id: 101,
                title: "What is Physics? - Detailed Explanation",
                duration: "6:20",
                thumbnail: "/placeholder.svg?height=150&width=250",
                videoUrl: "#",
              },
              {
                id: 102,
                title: "Physics in Daily Life",
                duration: "4:15",
                thumbnail: "/placeholder.svg?height=150&width=250",
                videoUrl: "#",
              },
            ],
          },
          {
            id: 2,
            title: "Branches of Physics",
            content:
              "Classical mechanics, thermodynamics, electromagnetism, quantum mechanics, and relativity are the main branches of physics.",
            downloadUrl: "#",
            videos: [
              {
                id: 103,
                title: "Classical vs Modern Physics",
                duration: "8:30",
                thumbnail: "/placeholder.svg?height=150&width=250",
                videoUrl: "#",
              },
            ],
          },
        ],
        quizzes: [
          {
            id: 1,
            title: "Physics Fundamentals Quiz",
            description: "Test your understanding of basic physics concepts",
            duration: "10 min",
            totalQuestions: 5,
            passingScore: 70,
            isCompleted: true,
            userScore: 85,
            attempts: 1,
            maxAttempts: 3,
            questions: [
              {
                id: 1,
                question: "What is physics?",
                type: "multiple-choice",
                options: [
                  "The study of living organisms",
                  "The study of matter and energy",
                  "The study of chemical reactions",
                  "The study of human behavior",
                ],
                correctAnswer: 1,
                explanation: "Physics is the fundamental science that studies matter, energy, and their interactions.",
                points: 20,
              },
              {
                id: 2,
                question: "Physics deals with both matter and energy.",
                type: "true-false",
                options: ["True", "False"],
                correctAnswer: 0,
                explanation: "Physics indeed studies both matter and energy and how they interact.",
                points: 20,
              },
              {
                id: 3,
                question: "Name one branch of physics that deals with motion.",
                type: "fill-blank",
                correctAnswer: "mechanics",
                explanation: "Mechanics is the branch of physics that deals with motion and forces.",
                points: 20,
              },
              {
                id: 4,
                question: "Which of the following is NOT a branch of physics?",
                type: "multiple-choice",
                options: ["Thermodynamics", "Quantum Mechanics", "Biochemistry", "Electromagnetism"],
                correctAnswer: 2,
                explanation: "Biochemistry is a branch of chemistry, not physics.",
                points: 20,
              },
              {
                id: 5,
                question: "Physics helps us understand the universe around us.",
                type: "true-false",
                options: ["True", "False"],
                correctAnswer: 0,
                explanation: "Physics provides fundamental understanding of how the universe works.",
                points: 20,
              },
            ],
          },
          {
            id: 2,
            title: "Physics Applications Quiz",
            description: "Explore real-world applications of physics",
            duration: "8 min",
            totalQuestions: 4,
            passingScore: 75,
            isCompleted: false,
            attempts: 0,
            maxAttempts: 2,
            questions: [
              {
                id: 6,
                question: "Which physics principle explains how airplanes fly?",
                type: "multiple-choice",
                options: ["Bernoulli's Principle", "Newton's Third Law", "Both A and B", "Neither A nor B"],
                correctAnswer: 2,
                explanation: "Both Bernoulli's Principle and Newton's Third Law contribute to flight.",
                points: 25,
              },
              {
                id: 7,
                question: "GPS systems rely on Einstein's theory of relativity.",
                type: "true-false",
                options: ["True", "False"],
                correctAnswer: 0,
                explanation: "GPS satellites must account for relativistic effects to maintain accuracy.",
                points: 25,
              },
              {
                id: 8,
                question: "What type of energy is stored in a stretched rubber band?",
                type: "fill-blank",
                correctAnswer: "potential",
                explanation: "Elastic potential energy is stored in deformed elastic objects.",
                points: 25,
              },
              {
                id: 9,
                question: "Which law explains why we feel pushed back in a car when it accelerates?",
                type: "multiple-choice",
                options: ["Newton's First Law", "Newton's Second Law", "Newton's Third Law", "Law of Gravitation"],
                correctAnswer: 0,
                explanation: "Newton's First Law (inertia) explains this phenomenon.",
                points: 25,
              },
            ],
          },
        ],
      },
      {
        id: 2,
        title: "Scientific Method",
        duration: "20 min",
        isCompleted: true,
        videos: [
          {
            id: 3,
            title: "Scientific Method Explained",
            duration: "15:20",
            thumbnail: "/placeholder.svg?height=200&width=300",
            videoUrl: "#",
          },
        ],
        notes: [
          {
            id: 3,
            title: "Steps of Scientific Method",
            content:
              "Observation, hypothesis formation, experimentation, analysis, and conclusion form the core of scientific inquiry.",
            downloadUrl: "#",
            videos: [
              {
                id: 104,
                title: "Scientific Method Step by Step",
                duration: "10:45",
                thumbnail: "/placeholder.svg?height=150&width=250",
                videoUrl: "#",
              },
              {
                id: 105,
                title: "Famous Scientific Experiments",
                duration: "12:20",
                thumbnail: "/placeholder.svg?height=150&width=250",
                videoUrl: "#",
              },
            ],
          },
        ],
        quizzes: [
          {
            id: 3,
            title: "Scientific Method Quiz",
            description: "Test your knowledge of scientific methodology",
            duration: "12 min",
            totalQuestions: 6,
            passingScore: 80,
            isCompleted: false,
            attempts: 0,
            maxAttempts: 3,
            questions: [
              {
                id: 10,
                question: "What is the first step in the scientific method?",
                type: "multiple-choice",
                options: ["Hypothesis", "Observation", "Experiment", "Conclusion"],
                correctAnswer: 1,
                explanation: "Observation is typically the first step that leads to questions.",
                points: 16,
              },
              {
                id: 11,
                question: "A hypothesis must be testable.",
                type: "true-false",
                options: ["True", "False"],
                correctAnswer: 0,
                explanation: "A hypothesis must be testable and falsifiable to be scientific.",
                points: 17,
              },
              {
                id: 12,
                question: "What comes after forming a hypothesis?",
                type: "fill-blank",
                correctAnswer: "experiment",
                explanation: "After forming a hypothesis, scientists design experiments to test it.",
                points: 17,
              },
              {
                id: 13,
                question: "Which of these is NOT a step in the scientific method?",
                type: "multiple-choice",
                options: ["Observation", "Publication", "Analysis", "Conclusion"],
                correctAnswer: 1,
                explanation: "While publication is important, it's not a core step of the scientific method.",
                points: 16,
              },
              {
                id: 14,
                question: "Scientists should be objective in their analysis.",
                type: "true-false",
                options: ["True", "False"],
                correctAnswer: 0,
                explanation: "Objectivity is crucial for valid scientific conclusions.",
                points: 17,
              },
              {
                id: 15,
                question: "What should you do if your hypothesis is proven wrong?",
                type: "fill-blank",
                correctAnswer: "revise",
                explanation: "Scientists should revise their hypothesis based on experimental results.",
                points: 17,
              },
            ],
          },
        ],
      },
      {
        id: 3,
        title: "Units and Measurements",
        duration: "25 min",
        isCompleted: true,
        videos: [
          {
            id: 4,
            title: "Understanding SI Units",
            duration: "18:15",
            thumbnail: "/placeholder.svg?height=200&width=300",
            videoUrl: "#",
          },
        ],
        notes: [
          {
            id: 4,
            title: "SI Units",
            content: "The International System of Units (SI) provides a standard for measurements worldwide.",
            downloadUrl: "#",
            videos: [
              {
                id: 106,
                title: "SI Base Units Explained",
                duration: "7:30",
                thumbnail: "/placeholder.svg?height=150&width=250",
                videoUrl: "#",
              },
            ],
          },
          {
            id: 5,
            title: "Dimensional Analysis",
            content: "A method to check equations and convert between different units using dimensional consistency.",
            downloadUrl: "#",
            videos: [
              {
                id: 107,
                title: "Dimensional Analysis Examples",
                duration: "9:15",
                thumbnail: "/placeholder.svg?height=150&width=250",
                videoUrl: "#",
              },
              {
                id: 108,
                title: "Unit Conversion Tricks",
                duration: "5:40",
                thumbnail: "/placeholder.svg?height=150&width=250",
                videoUrl: "#",
              },
            ],
          },
        ],
        quizzes: [
          {
            id: 4,
            title: "Units and Measurements Quiz",
            description: "Master the fundamentals of scientific measurements",
            duration: "15 min",
            totalQuestions: 7,
            passingScore: 70,
            isCompleted: true,
            userScore: 92,
            attempts: 1,
            maxAttempts: 3,
            questions: [],
          },
        ],
      },
      {
        id: 4,
        title: "Vectors and Scalars",
        duration: "30 min",
        isCompleted: false,
        videos: [
          {
            id: 5,
            title: "Vector Mathematics",
            duration: "22:40",
            thumbnail: "/placeholder.svg?height=200&width=300",
            videoUrl: "#",
          },
        ],
        notes: [
          {
            id: 6,
            title: "Vector Basics",
            content: "Vectors have both magnitude and direction, while scalars have only magnitude.",
            downloadUrl: "#",
            videos: [
              {
                id: 109,
                title: "Vector vs Scalar Examples",
                duration: "6:50",
                thumbnail: "/placeholder.svg?height=150&width=250",
                videoUrl: "#",
              },
            ],
          },
        ],
        quizzes: [
          {
            id: 5,
            title: "Vectors vs Scalars Quiz",
            description: "Distinguish between vectors and scalars",
            duration: "10 min",
            totalQuestions: 5,
            passingScore: 60,
            isCompleted: false,
            attempts: 0,
            maxAttempts: 3,
            questions: [],
          },
        ],
      },
    ],
  }